"""empty message

Revision ID: cb46ab011884
Revises: 
Create Date: 2026-07-28 15:32:27.094709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cb46ab011884'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilisateur_email'))
        batch_op.drop_index(batch_op.f('ix_utilisateur_id'))

    op.drop_table('utilisateur')
    with op.batch_alter_table('ferme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ferme_code_unique'))

    op.drop_table('ferme')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ferme',
    sa.Column('code_unique', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('adresse', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment="Date et heure de création de l'enregistrement"),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Date et heure de la dernière modification'),
    sa.PrimaryKeyConstraint('code_unique', name=op.f('ferme_pkey'))
    )
    with op.batch_alter_table('ferme', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ferme_code_unique'), ['code_unique'], unique=False)

    op.create_table('utilisateur',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment="Date et heure de création de l'enregistrement"),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Date et heure de la dernière modification'),
    sa.PrimaryKeyConstraint('id', name=op.f('utilisateur_pkey'))
    )
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilisateur_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utilisateur_email'), ['email'], unique=True)

    # ### end Alembic commands ###
